Repository readme-experts/cyberchef, pull requests merged in 2023-06, with the labels that each got.

#73 feat: http services(frontend)
  src/client/src/app/actions/account/addFavoriteRecipe.js
  src/client/src/app/actions/account/addUserRecipe.js
  src/client/src/app/actions/account/deleteFavoriteRecipe.js
  src/client/src/app/actions/account/deleteUserRecipe.js
  src/client/src/app/actions/account/loadFavoriteRecipes.js
  src/client/src/app/actions/account/loadUserRecipes.js
  src/client/src/app/actions/account/loginUser.js
  src/client/src/app/actions/account/registerUser.js
  src/client/src/app/slices/accountSlice.js
  src/client/src/app/store.js
  src/client/src/app/utils/thunkErrorWrapper.js
  src/client/src/pages/SearchRecipes.jsx
  src/client/src/pages/User.jsx
  src/client/src/services/AuthService.js
  src/client/src/services/BaseService.js
  src/client/src/services/RecipeService.js
  src/client/src/services/UserService.js
  src/client/src/services/errors/AuthError.js
  src/client/src/services/errors/BaseError.js
  src/client/src/services/errors/RecipeError.js
  src/client/src/services/errors/UserError.js
Labels: enhancement, frontend

#82 Parser
  package.json
  src/parser/data/recipes.json
  src/parser/handlers/infoHandler.js
  src/parser/handlers/saver.js
Labels: enhancement, Backend, Tests

#84 Fix nest build bug
  src/client/src/app/actions/account/loadFavoriteRecipes.ts
  src/server/tsconfig.json
Labels: bug
